name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++, clang++]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run the tests
        env:
          COMPILER: ${{ matrix.compiler }}
        run: ./build.sh $COMPILER -j4 && cd regression && make test
  lint:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Install git-clang-format
        run: |
          wget https://raw.githubusercontent.com/llvm-mirror/clang/master/tools/clang-format/git-clang-format
          sudo install -t /usr/bin git-clang-format
      - name: Get the latest master
        run: git fetch origin master:master
      - name: Run clang-format
        run: git clang-format master
      - name: Diff
        run: git diff --exit-code
