name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++, clang++]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run the tests
        env:
          COMPILER: ${{ matrix.compiler }}
        run: ./build.sh $COMPILER -j4 && cd regression && make test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the latest master
        run: git fetch origin master:master
      - name: Run lint
        run: scripts/run_lint.sh master HEAD
